FamilyName=Cyclone3
VendorName=Altera
SynthArchName=CYCLONE
LogFileName=Z:\Dropbox\M2FS-Dropbox\circuit boards\M2FS FLS Data Formatter\FPGA Project\ProjectOutputs\DataFormatter\M2FS_FLS_Data_Formatter_8_14_2012.synthlog
OutputFileName=Z:\Dropbox\M2FS-Dropbox\circuit boards\M2FS FLS Data Formatter\FPGA Project\ProjectOutputs\DataFormatter\M2FS_FLS_Data_Formatter_8_14_2012.edn
BFLFileName=Z:\Dropbox\M2FS-Dropbox\circuit boards\M2FS FLS Data Formatter\FPGA Project\ProjectOutputs\DataFormatter\M2FS_FLS_Data_Formatter_8_14_2012.bfl
Entity=M2FS_FLS_Data_Formatter_8_14_2012
VerilogMode=1
VHDL87=0
InsertIOBuffers=True
SDB_MaxMultipliers=2147483647
InferRam=Auto
RomStyle=Logic
SisOptimizationLevel=Medium
SDB_ActiveLowAsynPreset=False
SDB_ActiveLowAsynReset=False
SDB_ActiveLowTristate=True
SDB_AlteraAdder=True
SDB_AlteraLpmAddSub=True
SDB_AlteraLpmCompare=True
SDB_AlteraLpmMultiply=True
SDB_AlteraLVDS=False
SDB_EdifBitvecInHex=False
SDB_EnableAsynFlipFlop=True
SDB_EnableLatch=False
SDB_EnableSyncFlipFlop=False
SDB_LatticeCCU2=False
SDB_LatticeCCU2B=False
SDB_LatticeFADD2=False
SDB_LatticeFADD2B=False
SDB_LatticeFSUB2=False
SDB_LatticeFSUB2B=False
SDB_LatticeMult=False
SDB_LatticeMultB=False
SDB_TristateInternalToMux=False
SDB_TristatePushToTop=False
SDB_TristateToMux=False
SDB_XilinxMacroAdder=False
SDB_XilinxMacroMux=False
SDB_XilinxMult=False
SDB_XilinxMuxF56=False
SDB_XilinxMuxF78=False
